### ISSUE TITLE
I have some error with correlation :ImportError: No module named 'inpainting.models.correlation_package._ext.correlation._correlation'

### ISSUE THREAD

**Issue by PengzeZhang** [zllrunning/video-object-removal#14]
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from inpaint import inpaint
  File "/media/data2/zhangpz/video-object-removal-master/inpaint.py", line 5, in <module>
    from inpainting.model import generate_model
  File "/media/data2/zhangpz/video-object-removal-master/inpainting/model.py", line 3, in <module>
    from inpainting.models import vinet
  File "/media/data2/zhangpz/video-object-removal-master/inpainting/models/vinet.py", line 6, in <module>
    from inpainting.models.flow_modules import (WarpingLayer, LongFlowNetCorr, MaskEstimator_ )
  File "/media/data2/zhangpz/video-object-removal-master/inpainting/models/flow_modules.py", line 7, in <module>
    from inpainting.models.correlation_package.modules.correlation import Correlation
  File "/media/data2/zhangpz/video-object-removal-master/inpainting/models/correlation_package/modules/correlation.py", line 3, in <module>
    from ..functions.correlation import CorrelationFunction
  File "/media/data2/zhangpz/video-object-removal-master/inpainting/models/correlation_package/functions/correlation.py", line 3, in <module>
    from .._ext import correlation
  File "/media/data2/zhangpz/video-object-removal-master/inpainting/models/correlation_package/_ext/correlation/__init__.py", line 3, in <module>
    from ._correlation import lib as _lib, ffi as _ffi
ImportError: No module named 'inpainting.models.correlation_package._ext.correlation._correlation'
I have this error. Thank you!

**Comment by xyzdcgan** [comment]
I am getting below error after all frames are executed and also results are save in result directory in data folder but no video is generated/saved.

Number of model parameters: 14115364
error in Correlation_forward_cuda_kernel: invalid device function
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    inpaint(args)
  File "/home/ios/IP_IOS_AI_ENQ/face-edit/video-object-removal/inpaint.py", line 154, in inpaint
    outputs, _, _, _, _ = model(masked_inputs_, masks_, lstm_state, prev_feed, t)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ios/IP_IOS_AI_ENQ/face-edit/video-object-removal/inpainting/models/vinet.py", line 174, in forward
    flow2 = self.flownet(f1, f2)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ios/IP_IOS_AI_ENQ/face-edit/video-object-removal/inpainting/models/flow_modules.py", line 132, in forward
    corr = self.corr(x1.contiguous(), x2.contiguous())
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ios/IP_IOS_AI_ENQ/face-edit/video-object-removal/inpainting/models/correlation_package/modules/correlation.py", line 17, in forward
    result = CorrelationFunction(self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)(input1, input2)
  File "/home/ios/IP_IOS_AI_ENQ/face-edit/video-object-removal/inpainting/models/correlation_package/functions/correlation.py", line 30, in forward
    self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: aborting at /home/ios/IP_IOS_AI_ENQ/face-edit/video-object-removal/inpainting/models/correlation_package/src/correlation_cuda.c:88

**Comment by yarik1988** [comment]
Before executing
`bash install.sh`
you need to change -arch=sm_52 option in the files
inpainting/lib/channelnorm_package/make.sh
inpainting/lib/correlation_package/make.sh
inpainting/lib/resample2d_package/make.sh
inpainting/models/correlation_package/make.sh
according to the web-site
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by kedarSedai** [comment]
what does the file look like after changing -arch=sm_52  options?

**Comment by yarik1988** [comment]
> what does the file look like after changing -arch=sm_52 options?

You need to change line 9 in these 4 files
```
nvcc -c -o ChannelNorm_kernel.o ChannelNorm_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_52 -I ${TORCH}/lib/include/TH -I ${TORCH}/lib/include/THC
```
instead of -arch=sm_52 put your GPU architecture

**Comment by devendraswamy** [comment]
I am facing same error with ubuntu 16 , cuda 10 version , please help me to resolve the issue and even i changed -arch as per my gpu architecture..
