### ISSUE TITLE
error in inpaint

### ISSUE THREAD

**Issue by JeetShah25** [zllrunning/video-object-removal#15]
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from inpaint import inpaint
  File "E:\pytorch\video-object-removal\inpaint.py", line 5, in <module>
    from inpainting.model import generate_model
  File "E:\pytorch\video-object-removal\inpainting\model.py", line 3, in <module>
    from inpainting.models import vinet
  File "E:\pytorch\video-object-removal\inpainting\models\vinet.py", line 6, in <module>
    from inpainting.models.flow_modules import (WarpingLayer, LongFlowNetCorr, MaskEstimator_ )
  File "E:\pytorch\video-object-removal\inpainting\models\flow_modules.py", line 7, in <module>
    from inpainting.models.correlation_package.modules.correlation import Correlation
  File "E:\pytorch\video-object-removal\inpainting\models\correlation_package\modules\correlation.py", line 3, in <module>
    from ..functions.correlation import CorrelationFunction
  File "E:\pytorch\video-object-removal\inpainting\models\correlation_package\functions\correlation.py", line 3, in <module>
    from .._ext import correlation
ModuleNotFoundError: No module named 'inpainting.models.correlation_package._ext'

**Comment by ulatekh** [comment]
Did you follow the build instructions?
That should have been built when you ran "bash install.sh" from the "inpainting" directory.
