### ISSUE TITLE
Error when running bash install.sh

### ISSUE THREAD

**Issue by CommandoHuan** [zllrunning/video-object-removal#27]
Hello everyone, i just got the following error when running bash install.sh:

Compiling correlation kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch.utils.ffi
  File "/home/huan/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling resample2d kernels by nvcc...
Resample2d_kernel.cu:1:10: fatal error: THC.h: No such file or directory
 #include <THC.h>
          ^~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch.utils.ffi
  File "/home/huan/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling channelnorm kernels by nvcc...
ChannelNorm_kernel.cu:1:10: fatal error: THC.h: No such file or directory
 #include <THC.h>
          ^~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch.utils.ffi
  File "/home/huan/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling correlation kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    import torch.utils.ffi
  File "/home/huan/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
(myenv) huan@HuanUbt:~/video-object-removal/inpainting$ 

Is anyone can help me?

**Comment by CommandoHuan** [comment]
My PC is Ubuntu 18.04 LTS, Python 3.6, Pytorch 1.4, CUDA 10.1, GTX1070 GPU.

**Comment by OnlyFlashEobard** [comment]
change 
``from torch.utils.ffi import create_extension
to
``from torch.utils.cpp_extension import BuildExtension

and change
``ffi = create_extension(...) 
to
``ffi = BuildExtension(...)

**Comment by OnlyFlashEobard** [comment]
change 
``from torch.utils.ffi import create_extension``
to
``from torch.utils.cpp_extension import BuildExtension``
and change
``ffi = create_extension(...)``
to
``ffi = BuildExtension(...)``

**Comment by dueToLife** [comment]
I used to meet this also. It's because your nvcc can't find THC.h and THCGeneric.h. see [this line](https://github.com/zllrunning/video-object-removal/blob/121f0b8359a534bae6afcd31fd0f486d10ee712a/inpainting/lib/channelnorm_package/make.sh#L2) and [this line](https://github.com/zllrunning/video-object-removal/blob/121f0b8359a534bae6afcd31fd0f486d10ee712a/inpainting/lib/channelnorm_package/make.sh#L9). Check if it is a true path of pytorch:
```py
print(os.path.dirname(torch.__file__))
```

**Comment by dueToLife** [comment]
And due to your high pytorch version，some api was deprecated，use their substitute in pytorch 1.0+

**Comment by CommandoHuan** [comment]
Thank all bros. Let me do.
