### ISSUE TITLE
undefined symbol: __cudaRegisterFatBinaryEnd if run demo.py

### ISSUE THREAD

**Issue by yaroslavmavliutov** [zllrunning/video-object-removal#31]
Hello! When I try ro run demo.py , i obtain an error

Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from inpaint import inpaint
  File "/content/video-object-removal/inpaint.py", line 5, in <module>
    from inpainting.model import generate_model
  File "/content/video-object-removal/inpainting/model.py", line 3, in <module>
    from inpainting.models import vinet
  File "/content/video-object-removal/inpainting/models/vinet.py", line 6, in <module>
    from inpainting.models.flow_modules import (WarpingLayer, LongFlowNetCorr, MaskEstimator_ )
  File "/content/video-object-removal/inpainting/models/flow_modules.py", line 7, in <module>
    from inpainting.models.correlation_package.modules.correlation import Correlation
  File "/content/video-object-removal/inpainting/models/correlation_package/modules/correlation.py", line 3, in <module>
    from ..functions.correlation import CorrelationFunction
  File "/content/video-object-removal/inpainting/models/correlation_package/functions/correlation.py", line 3, in <module>
    from .._ext import correlation
  File "/content/video-object-removal/inpainting/models/correlation_package/_ext/correlation/__init__.py", line 3, in <module>
    from ._correlation import lib as _lib, ffi as _ffi
ImportError: /content/video-object-removal/inpainting/models/correlation_package/_ext/correlation/_correlation.so: undefined symbol: __cudaRegisterFatBinaryEnd

**Comment by yaroslavmavliutov** [comment]
I used pytorch 0.4.0, cuda 8.0 (tried 9.0 also)

**Comment by dueToLife** [comment]
I met this problem under pytorch 0.4.0, python 3.5.6, cuda 11.1, gcc 7.6 and solved it by changing environment to **pytorch 0.4.0, python 3.5.6, cuda 9.0, gcc 5.5.0**. After changing env, rerun .sh files to compile dependencies. Hope it useful.

**Comment by Cola-any** [comment]
> I met this problem under pytorch 0.4.0, python 3.5.6, cuda 11.1, gcc 7.6 and solved it by changing environment to **pytorch 0.4.0, python 3.5.6, cuda 9.0, gcc 5.5.0**. After changing env, rerun .sh files to compile dependencies. Hope it useful.
that is useful, gcc 5.4 also works!
