### ISSUE TITLE
ImportError: No module named inpainting.davis

### ISSUE THREAD

**Issue by K4Fr** [zllrunning/video-object-removal#4]
How do I fix this error I am getting?

:~/video-object-removal$ python demo.py --data /home/user/Desktop/VID_151890412_145812_234.mp4
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from inpaint import inpaint
  File "/home/user/video-object-removal/inpaint.py", line 4, in <module>
    from inpainting.davis import DAVIS
ImportError: No module named inpainting.davis

**Comment by zllrunning** [comment]
Sorry for the late reply. Try to add __init__.py file in inpainting folder and retry it.

**Comment by zllrunning** [comment]
Sorry for the late reply. Try to add `__init__.py` file in `inpainting` folder and retry it.

**Comment by magneter** [comment]
ImportError: cannot import name 'region' ,I have a same question .
It occured in file "__init__ "

**Comment by magneter** [comment]
in __init__.py   , from . import region

**Comment by ulatekh** [comment]
Using python3 should take care of this error.
