### ISSUE TITLE
I have a problem with importing torch

### ISSUE THREAD

**Issue by bleachjade** [zllrunning/video-object-removal#5]
sorry I'm new here, can anybody help?
------------------------------------------
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from mask import mask
  File "C:\Users\Jade\video-object-removal\mask.py", line 8, in <module>
    from get_mask.test import *
  File "C:\Users\Jade\video-object-removal\get_mask\test.py", line 16, in <module>
    from get_mask.utils.load_helper import load_pretrain
  File "C:\Users\Jade\video-object-removal\get_mask\utils\load_helper.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by zllrunning** [comment]
You do not install PyTorch. Furthermore, this repo needs exactly Pytorch 0.4.0.

**Comment by Brucepk** [comment]
> You do not install PyTorch. Furthermore, this repo needs exactly Pytorch 0.4.0.

There are only two versions of the official website, 0.1.2 and 1.0.2, no version 0.4.0

**Comment by Zana-hex** [comment]
> 
> 
> You do not install PyTorch. Furthermore, this repo needs exactly Pytorch 0.4.0.

Pytorch 0.4.0 or Torchvision 0.4.0?
